# Mini tutorial de NumPy

*Esta notebook fue creada originalmente como un blog post por [Raúl E. López Briega](http://relopezbriega.github.io) para el [sitio de capacitaciones de IAAR](https://iaarhub.github.io/). El contenido esta bajo la licencia BSD.*

<img src="https://bids.berkeley.edu/sites/default/files/styles/400x225/public/projects/numpy_project_page.jpg?itok=flrdydei" title="numpy" alt="numpy">

[NumPy](http://www.numpy.org) es el principal paquete para la computación científica con [Python](https://www.python.org/)

Este mini tutorial esta orientado a una introducción de Python para la Ciencia de Datos. ***Pueden contactarme [aquí](http://relopezbriega.github.io/) para cualquier tipo de sugerencias!***. Basado en la cheat sheet de [JulianGaal](https://github.com/juliangaal/python-cheat-sheet/blob/master/NumPy/NumPy.md)

## Índice
1. [Numpy básico](#basics)
    - [Placeholders](#place)
    - [Ejemplos](#ex)
2. [Arrays](#arrays)
    - [Propiedades](#props)
    - [Copiando/Ordenando](#gops)
      * [Ejemplos](#array-Ejemplo)
    - [Manipulación de Arrays](#man)
      * [Agregando/Quitando Elementos](#addrem)
      * [Combinando Arrays](#comb)
      * [Dividiendo Arrays](#split)
      * [Mas](#more)
3. [Matemáticas](#maths)
    - [Operaciones aritméticas](#ops)
      * [Ejemplos](#operations-Ejemplos)
    - [Comparaciones](#comparison)
      * [Ejemplos](#comparison-Ejemplo)
    - [Estadística básica](#stats)
    - [Mas funciones](#more_func)
4. [Slicing y Subsetting](#ss)
    - [Ejemplos](#exp)
5. [Trucos](#Trucos)
6. [Créditos](#creds)


## Numpy básico <a name="basics"></a>

Una de las funciones más utilizadas de [NumPy](http://www.numpy.org) son los *arreglos o arrays*: La principal diferencia entre las *listas de python* y los *arrays de numpy* esta dada por la velocidad y las funcionalidades adicionales que poseen estas últimas. Las *listas* solo nos dan operaciones básicas, pero los *arrays de numpy* nos agregan FFTs, convoluciones, búsquedas rápidas, estadística, álgebra lineal, histogramas, entre muchas otras cosas.</br>
La más importante ventaja que poseen los *arrays de numpy* para la ciencia de datos, es la habilidad de hacer cálculos a nivel de los elementos. 

`eje 0` siempre se refiere a una fila 

`eje 1` siempre se refiere a una columna

| Operador       | Descripción    | Documentación |
| :------------- | :------------- | :--------|
|`np.array([1,2,3])`|1d array|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.array.html#numpy.array)|
|`np.array([(1,2,3),(4,5,6)])`|2d array|ver arriba|
|`np.arange(start,stop,step)`|array desde un rango|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html)|

### Placeholders <a name="place"></a>
| Operador | Descripción |Documentación|
| :------------- | :------------- |:---------- |
|`np.linspace(0,2,9)`|Agrega valores equidistantes desde el intervalo hasta el largo del array |[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linspace.html)|
|`np.zeros((1,2))`|Crea un array de ceros|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.zeros.html)|
|`np.ones((1,2))`|Crea un array de unos|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html#numpy.ones)|
|`np.random.random((5,5))`|Crea un array de números aleatorios|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.random.html)|
|`np.empty((2,2))`|Crea un array vacío|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.empty.html)|

### Ejemplos <a name="ex"></a>

In [2]:
# Convencion para importar numpy 
import numpy as np

In [3]:
# 1 dimension
x = np.array([1,2,3])
# 2 dimensiones
y = np.array([(1,2,3),(4,5,6)])
x, y

(array([1, 2, 3]), array([[1, 2, 3],
        [4, 5, 6]]))

In [4]:
# con int
x = np.arange(3)
x

array([0, 1, 2])

In [5]:
# con float
y = np.arange(3.0)
y

array([ 0.,  1.,  2.])

In [6]:
# rango
x = np.arange(3,7)
x

array([3, 4, 5, 6])

In [7]:
# rango con intervalo
y = np.arange(3,7,2)
y

array([3, 5])

## Arrays <a name="arrays"></a>

### Propiedades de los Arrays <a name="props"></a>
|Sintaxis|Descripción|Documentación|
|:-------------|:-------------|:-----------|
|`array.shape`|Dimensiones (Filas,Columnas)|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.shape.html)|
|`len(array)`|Largo de Arrays|[link](https://docs.python.org/3.5/library/functions.html#len)|
|`array.ndim`|Numero de dimensiones de Array|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.ndim.html)|
|`array.size`|Números de Elementos de Array|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.size.html)|
|`array.dtype`|Tipo de Datos|[link](https://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html)|
|`array.astype(type)`|Convertir tipo de datos|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.astype.html)|
|`type(array)`|Tipo de Array|[link](https://docs.scipy.org/doc/numpy/user/basics.types.html)|

### Copiando/Ordenando <a name="gops"></a>
| Operador | Descripciones     | Documentación |
| :------------- | :------------- | :----------- |
|`np.copy(array)`|Crea una copia del array|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.copy.html)|
|`other = array.copy()`|Crea una copia profunda del array|ver arriba|
|`array.sort()`|Ordena un Array|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.sort.html)|
|`array.sort(axis=0)`|Ordena los ejes del Array|ver arriba|

#### Ejemplos <a name="array-Ejemplo"></a>

In [9]:
# Ordenar. Ordenar en orden ascendente
y = np.array([10, 9, 8, 7, 6, 5, 4, 3, 2, 1])
y.sort()
y

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Manipulación de Arrays<a name="man"></a>

### Agregando o quitando elementos <a name="addrem"></a>
|Operador|Descripción|Documentación|
|:-----------|:--------|:---------|
|`np.append(a,b)`|Agrega items al array|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.append.html)|
|`np.insert(array, 1, 2, axis)`|Inserta items al arrays en ejes 0 o 1|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.insert.html)|
|`array.resize((2,4))`|Redimensiona el array a la forma(2,4)|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.resize.html)|
|`np.delete(array,1,axis)`|Elimina items del array|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.delete.html)|

### Combinando Arrays <a name="comb"></a>
|Operador|Descripción|Documentación|
|:---------|:-------|:---------|
|`np.concatenate((a,b),axis=0)`|Concatena 2 arrays, agrega al final|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.concatenate.html)|
|`np.vstack((a,b))`|Apila array a nivel filas|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.vstack.html)|
|`np.hstack((a,b))`|Apila array a nivel columna|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.hstack.html#numpy.hstack)|

### Dividiendo Arrays <a name="split"></a>
|Operador|Descripción|Documentación|
|:---------|:-------|:------|
|`numpy.split()`||[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.split.html)|
|`np.array_split(array, 3)`|Divide un array en sub-arrays de (casi) idéntico tamaño|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.array_split.html#numpy.array_split)|
|`numpy.hsplit(array, 3)`|Divide el array en forma horizontal en el 3er índice |[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.hsplit.html#numpy.hsplit)|


### Mas <a name="more"></a>
|Operador|Descripción|Documentación|
|:--------|:--------|:--------|
|`other = ndarray.flatten()`|Aplana un array de 2d a una de 1d|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.flatten.html)|
|`array = np.transpose(other)`</br> `array.T` |Transpone el array|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.transpose.html)|


## Matemáticas <a name="maths"></a>

### Operaciones aritméticas <a name="ops"></a>
| Operador | Descripción     |Documentación|
| :------------- | :------------- |:---------|
|`np.add(x,y)`|Adición|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.add.html)|
|`np.substract(x,y)`|Substracción|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.subtract.html#numpy.subtract)|
|`np.divide(x,y)`|División|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.divide.html#numpy.divide)|
|`np.multiply(x,y)`|Multiplicación|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.multiply.html#numpy.multiply)|
|`np.sqrt(x)`|Raíz cuadrada|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.sqrt.html#numpy.sqrt)|
|`np.sin(x)`|Seno a nivel elemento|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.sin.html#numpy.sin)|
|`np.cos(x)`|Coseno a nivel elemento|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.cos.html#numpy.cos)|
|`np.log(x)`|Logaritmo natural a nivel elementos|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.log.html#numpy.log)|
|`np.dot(x,y)`|Producto escalar|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html)|

**Recordar:** Las operaciones con arrays de NumPy funcionan a nivel elemento.

#### Ejemplo <a name="operations-Ejemplos"></a>

In [10]:
# Si un array de 1d es sumada a otra de 2d, Numpy elije 
# la array con dimensión más pequeña y la suma con la de
# dimensión más grande
a = np.array([1, 2, 3])
b = np.array([(1, 2, 3), (4, 5, 6)])
print(np.add(a, b))

[[2 4 6]
 [5 7 9]]


### Comparación <a name="comparison"></a>
| Operador | Descripción | Documentación |
| :------------- | :------------- |:---------|
|`==`|Igual a|[link](https://docs.python.org/2/library/stdtypes.html)|
|`!=`|No igual a|[link](https://docs.python.org/2/library/stdtypes.html)|
|`<`|Menor que|[link](https://docs.python.org/2/library/stdtypes.html)|
|`>`|Mayor que|[link](https://docs.python.org/2/library/stdtypes.html)|
|`<=`|Menor o igual que|[link](https://docs.python.org/2/library/stdtypes.html)|
|`>=`|Mayor o igual que|[link](https://docs.python.org/2/library/stdtypes.html)|
|`np.array_equal(x,y)`|Comparación a nivel elemento|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.array_equal.html)|

#### Ejemplo <a name="comparison-Ejemplo"></a>

In [5]:
# Utilizando operadores de comparación creará un array de tipo booleano.
z = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
c = z < 6
print(c)

[ True  True  True  True  True False False False False False]


### Estadística básica <a name="stats"></a>
| Operador | Descripción    | Documentación |
| :------------- | :------------- |:--------- |
|`array.mean()`</br>`np.mean(array)`|Media aritmética|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html#numpy.mean)|
|`np.median(array)`|Mediana|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.median.html#numpy.median)|
|`array.corrcoef()`|Coeficiente de correlación|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.corrcoef.html#numpy.corrcoef)|
|`array.std(array)`|Desvío estándar|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.std.html#numpy.std)|

### Mas funciones<a name="more_func"></a>
| Operador | Descripción    | Documentación |
| :------------- | :------------- |:--------- |
|`array.sum()`|Suma a nivel elementos|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.sum.html)|
|`array.min()`|Minimiza a nivel elementos|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.min.html)|
|`array.max(axis=0)`|Máximo valor de un determinado eje|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.max.html)|
|`array.cumsum(axis=0)`|Suma acumulada en un eje específico|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.cumsum.html)|


## Slicing y Subsetting <a name="ss"></a>
|Operador|Descripción|Documentación|
| :------------- | :------------- | :------------- |
|`array[i]`|array 1d al índice i|[link](https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html)|
|`array[i,j]`|array 2d al index[i][j]|ver arriba|
|`array[i<4]`|índice booleano, ver [Trucos](#Trucos)|ver arriba|
|`array[0:3]`|Selecciona items de indice 0, 1 y 2|ver arriba|
|`array[0:2,1]`|Selecciona items de filas 0 y 1 de la columna 1|ver arriba|
|`array[:1]`|Selecciona items de fila 0 (igual a array[0:1, :])|ver arriba|
|`array[1:2, :]`|Selecciona items de fila 1|ver arriba|
|`array[1,...]`|Igual a array[1,:,:]|ver arriba|
|`array[ : :-1]`|Reversa el `array`|ver arriba|


#### Ejemplos <a name="exp"></a>

In [7]:
# Seleccionando elementos.
b = np.array([(1, 2, 3), (4, 5, 6)])

# El índice *antes* de la coma refiere a filas,
# el índice *después* de la coma refiere a columnas.
print(b[0:1, 2])
print(b[:len(b), 2])
print(b[0, :])
print(b[0, 2:])
print(b[:, 0])

c = np.array([(1, 2, 3), (4, 5, 6)])
d = c[1:2, 0:2]
print(d)

[3]
[3 6]
[1 2 3]
[3]
[1 4]
[[4 5]]


## Trucos <a name="Trucos"></a>

Esta es una lista de ejemplos en progreso. Si conocen un buen truco, no duden en comentar para que sea incluido en el tutorial. 

In [3]:
# Truco de indices cuando trabajamos con 2 arrays
a = np.array([1,2,3,6,1,4,1])
b = np.array([5,6,7,8,3,1,2])

# Solo guardar a con indice dónde b == 1
other_a = a[b == 1]
print(other_a)

# Guardar todos las las posiciones excepto aquella en que b==1
other_other_a = a[b != 1]
print(other_other_a)

[4]
[1 2 3 6 1 1]


In [4]:
# Otra forma de trabajar con índices
x = np.array([4,6,8,1,2,6,9])
y = x > 5
print(x[y])

# Más compacta
x = np.array([1, 2, 3, 4, 4, 35, 212, 5, 5, 6])
print(x[x < 5])

[6 8 6 9]
[1 2 3 4 4]


## Créditos <a name="creds"></a>
[Datacamp](https://www.datacamp.com/home),
[Quandl](https://s3.amazonaws.com/quandl-static-content/Documents/Quandl+-+Pandas,+SciPy,+NumPy+Cheat+Sheet.pdf) y [Documentación oficial](https://docs.scipy.org/doc/numpy/)

*Este post fue escrito utilizando IPython notebook. Pueden descargar este [notebook](https://github.com/IAARhub/iaar_template/tree/master/content/notebooks/numpy_cheat_sheet.ipynb) o ver su version estática en [nbviewer](http://nbviewer.ipython.org/github/IAARhub/iaar_template/tree/master/content/notebooks/numpy_cheat_sheet.ipynb).*