# NumPy Cheat Sheet

<img src="https://bids.berkeley.edu/sites/default/files/styles/400x225/public/projects/numpy_project_page.jpg?itok=flrdydei" title="numpy" alt="numpy">

[NumPy](http://www.numpy.org) es el principal paquete para la computación científica con [Python](https://www.python.org/)

Este cheat sheet esta orientado a una introducción de Python para Ciencia de Datos. ***Pueden contactarme [aquí](http://relopezbriega.github.io/) para cualquier tipo de sugerencias!***. Basado en la cheat sheet de [JulianGaal](https://github.com/juliangaal/python-cheat-sheet/blob/master/NumPy/NumPy.md)

## Índice
1. [Numpy básico](#basics)
    - [Placeholders](#place)
    - [Ejemplos](#ex)
2. [Arrays](#arrays)
    - [Propiedades](#props)
    - [Copiando/Ordenando](#gops)
      * [Ejemplos](#array-Ejemplo)
    - [Manipulación de Arrays](#man)
      * [Agregando/Quitando Elementos](#addrem)
      * [Combinando Arrays](#comb)
      * [Dividiendo Arrays](#split)
3. [Matemáticas](#maths)
    - [Operaciones aritméticas](#ops)
      * [Ejemplos](#operations-Ejemplos)
    - [Comparaciones](#comparison)
      * [Ejemplos](#comparison-Ejemplo)
    - [Estadística básica](#stats)
    - [Mas](#more)
4. [Slicing y Subsetting](#ss)
    - [Ejemplos](#exp)
5. [Trucos](#Trucos)
6. [Créditos](#creds)

</br>

## Numpy básico <a name="basics"></a>

Una de las funciones más utilizadas de [NumPy](http://www.numpy.org) son los *arreglos o arrays*: La principal diferencia entre las *listas de python* y los *arrays de numpy* esta dada por la velocidad y las funcionalidades adicionales que poseen estas últimas. Las *listas* solo nos dan operaciones básicas, pero los *arrays de numpy* nos agregan FFTs, convoluciones, búsquedas rápidas, estadística, algebra lineal, histogramas, entre muchas otras.</br>
The most important difference for data science is the ability to do **element-wise calculations** with *NumPy arrays*.

`axis 0` always refers to row </br>
`axis 1` always refers to column

| Operator     | Description   | Documentation |
| :------------- | :------------- | :--------|
|`np.array([1,2,3])`|1d array|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.array.html#numpy.array)|
|`np.array([(1,2,3),(4,5,6)])`|2d array|see above|
|`np.arange(start,stop,step)`|range array|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html)|

### Placeholders <a name="place"></a>
| Operators | Description |Documentation|
| :------------- | :------------- |:---------- |
|`np.linspace(0,2,9)`|Add evenly spaced values btw interval to array of length |[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linspace.html)|
|`np.zeros((1,2))`|Create and array filled with zeros|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.zeros.html)|
|`np.ones((1,2))`|Creates an array filled with ones|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html#numpy.ones)|
|`np.random.random((5,5))`|Creates random array|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.random.html)|
|`np.empty((2,2))`|Creates an empty array|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.empty.html)|

### Ejemplos <a name="ex"></a>




In [2]:
import numpy as np

In [3]:
# 1 dimension
x = np.array([1,2,3])
# 2 dimensiones
y = np.array([(1,2,3),(4,5,6)])
x, y

(array([1, 2, 3]), array([[1, 2, 3],
        [4, 5, 6]]))

In [4]:
# con int
x = np.arange(3)
x

array([0, 1, 2])

In [5]:
# con float
y = np.arange(3.0)
y

array([ 0.,  1.,  2.])

In [6]:
# rango
x = np.arange(3,7)
x

array([3, 4, 5, 6])

In [7]:
# rango con intervalo
y = np.arange(3,7,2)
y

array([3, 5])

## Array <a name="arrays"></a>
### Array Propiedades <a name="props"></a>
|Syntax|Description|Documentation|
|:-------------|:-------------|:-----------|
|`array.shape`|Dimensions (Rows,Columns)|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.shape.html)|
|`len(array)`|Length of Array|[link](https://docs.python.org/3.5/library/functions.html#len)|
|`array.ndim`|Number of Array Dimensions|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.ndim.html)|
|`array.size`|Number of Array Elementos|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.size.html)|
|`array.dtype`|Data Type|[link](https://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html)|
|`array.astype(type)`|Converts to Data Type|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.astype.html)|
|`type(array)`|Type of Array|[link](https://docs.scipy.org/doc/numpy/user/basics.types.html)|

### Copiando/Ordenando <a name="grops"></a>
| Operators | Descriptions     | Documentation |
| :------------- | :------------- | :----------- |
|`np.copy(array)`|Creates copy of array|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.copy.html)|
|`other = array.copy()`|Creates deep copy of array|see above|
|`array.sort()`|Sorts an array|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.sort.html)|
|`array.sort(axis=0)`|Sorts axis of array|see above|

#### Ejemplos <a name="array-Ejemplo"></a>

In [9]:
# Ordenar. Ordenar en orde ascendente
y = np.array([10, 9, 8, 7, 6, 5, 4, 3, 2, 1])
y.sort()
y

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Array Manipulation Routines <a name="man"></a>

### Adding or Removing Elementos <a name="addrem"></a>
|Operator|Description|Documentation|
|:-----------|:--------|:---------|
|`np.append(a,b)`|Append items to array|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.append.html)|
|`np.insert(array, 1, 2, axis)`|Insert items into array at axis 0 or 1|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.insert.html)|
|`array.resize((2,4))`|Resize array to shape(2,4)|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.resize.html)|
|`np.delete(array,1,axis)`|Deletes items from array|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.delete.html)|

### Combining Arrays <a name="comb"></a>
|Operator|Description|Documentation|
|:---------|:-------|:---------|
|`np.concatenate((a,b),axis=0)`|Concatenates 2 arrays, adds to end|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.concatenate.html)|
|`np.vstack((a,b))`|Stack array row-wise|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.vstack.html)|
|`np.hstack((a,b))`|Stack array column wise|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.hstack.html#numpy.hstack)|

### Splitting Arrays <a name="split"></a>
|Operator|Description|Documentation|
|:---------|:-------|:------|
|`numpy.split()`||[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.split.html)|
|`np.array_split(array, 3)`|Split an array in sub-arrays of (nearly) identical size|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.array_split.html#numpy.array_split)|
|`numpy.hsplit(array, 3)`|Split the array horizontally at 3rd index|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.hsplit.html#numpy.hsplit)|


### More <a name="more"></a>
|Operator|Description|Documentation|
|:--------|:--------|:--------|
|`other = ndarray.flatten()`|Flattens a 2d array to 1d|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.flatten.html)|
|`array = np.transpose(other)`</br> `array.T` |Transpose array|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.transpose.html)|

</br>

## Matemáticas <a name="maths"></a>

### Operations <a name="ops"></a>
| Operator | Description     |Documentation|
| :------------- | :------------- |:---------|
|`np.add(x,y)`|Addition|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.add.html)|
|`np.substract(x,y)`|Subtraction|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.subtract.html#numpy.subtract)|
|`np.divide(x,y)`|Division|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.divide.html#numpy.divide)|
|`np.multiply(x,y)`|Multiplication|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.multiply.html#numpy.multiply)|
|`np.sqrt(x)`|Square Root|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.sqrt.html#numpy.sqrt)|
|`np.sin(x)`|Element-wise sine|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.sin.html#numpy.sin)|
|`np.cos(x)`|Element-wise cosine|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.cos.html#numpy.cos)|
|`np.log(x)`|Element-wise natural log|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.log.html#numpy.log)|
|`np.dot(x,y)`|Dot product|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html)|

Remember: NumPy array operations work element-wise.

#### Ejemplo <a name="operations-Ejemplos"></a>

In [10]:
# Si un array de 1d es sumada a otra de 2d, Numpy elije 
# la array con dimensión más pequeña y la suma con la de
# dimensión más grande
a = np.array([1, 2, 3])
b = np.array([(1, 2, 3), (4, 5, 6)])
print(np.add(a, b))

[[2 4 6]
 [5 7 9]]


### Comparison
| Operator | Description | Documentation |
| :------------- | :------------- |:---------|
|`==`|Equal|[link](https://docs.python.org/2/library/stdtypes.html)|
|`!=`|Not equal|[link](https://docs.python.org/2/library/stdtypes.html)|
|`<`|Smaller than|[link](https://docs.python.org/2/library/stdtypes.html)|
|`>`|Greater than|[link](https://docs.python.org/2/library/stdtypes.html)|
|`<=`|Smaller than or equal|[link](https://docs.python.org/2/library/stdtypes.html)|
|`>=`|Greater than or equal|[link](https://docs.python.org/2/library/stdtypes.html)|
|`np.array_equal(x,y)`|Array-wise comparison|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.array_equal.html)|

#### Ejemplo <a name="comparison-Ejemplo"></a>
```python
# Using comparison operators will create boolean NumPy arrays
z = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
c = z < 6
print(c)
>>> [ True  True  True  True  True False False False False False]
```
### Basic Statistics <a name="stats"></a>
| Operator | Description    | Documentation |
| :------------- | :------------- |:--------- |
|`array.mean()`</br>`np.mean(array)`|Mean|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html#numpy.mean)|
|`np.median(array)`|Median|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.median.html#numpy.median)|
|`array.corrcoef()`|Correlation Coefficient|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.corrcoef.html#numpy.corrcoef)|
|`array.std(array)`|Standard Deviation|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.std.html#numpy.std)|

### More <a name="more"></a>
| Operator | Description    | Documentation |
| :------------- | :------------- |:--------- |
|`array.sum()`|Array-wise sum|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.sum.html)|
|`array.min()`|Array-wise minimum value|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.min.html)|
|`array.max(axis=0)`|Maximum value of specified axis||
|`array.cumsum(axis=0)`|Cumulative sum of specified axis|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.cumsum.html)|

</br>

## Slicing and Subsetting <a name="ss"></a>
|Operator|Description|Documentation|
| :------------- | :------------- | :------------- |
|`array[i]`|1d array at index i|[link](https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html)|
|`array[i,j]`|2d array at index[i][j]|see above|
|`array[i<4]`|Boolean Indexing, see [Trucos](#Trucos)|see above|
|`array[0:3]`|Select items of index 0, 1 and 2|see above|
|`array[0:2,1]`|Select items of rows 0 and 1 at column 1|see above|
|`array[:1]`|Select items of row 0 (equals array[0:1, :])|see above|
|`array[1:2, :]`|Select items of row 1|see above|
[comment]: <> (|`array[1,...]`|equals array[1,:,:]|see above|)
|`array[ : :-1]`|Reverses `array`|see above|


#### Ejemplos <a name"exp"></a>
```python
b = np.array([(1, 2, 3), (4, 5, 6)])

# The index *before* the comma refers to *rows*,
# the index *after* the comma refers to *columns*
print(b[0:1, 2])
>>> [3]

print(b[:len(b), 2])
>>> [3 6]

print(b[0, :])
>>> [1 2 3]

print(b[0, 2:])
>>> [3]

print(b[:, 0])
>>> [1 4]

c = np.array([(1, 2, 3), (4, 5, 6)])
d = c[1:2, 0:2]
print(d)
>>> [[4 5]]

```

</br>

## Trucos <a name="Trucos"></a>
This is a growing list of Ejemplos. Know a good trick? Let me know [here](twitter.com/JulianGaal) or fork it and create a pull request.

*boolean indexing* (available as separate `.py` file [here](https://github.com/JulianGaal/python-cheat-sheet/blob/master/code/boolean-indexing.py)
```python
# Index trick when working with two np-arrays
a = np.array([1,2,3,6,1,4,1])
b = np.array([5,6,7,8,3,1,2])

# Only saves a at index where b == 1
other_a = a[b == 1]
#Saves every spot in a except at index where b != 1
other_other_a = a[b != 1]
```

```python
x = np.array([4,6,8,1,2,6,9])
y = x > 5
print(x[y])
>>> [6 8 6 9]

# Even shorter
x = np.array([1, 2, 3, 4, 4, 35, 212, 5, 5, 6])
print(x[x < 5])
>>> [1 2 3 4 4]

```

</br>

## Creditos <a name="creds"></a>
[Datacamp](https://www.datacamp.com/home),
[Quandl](https://s3.amazonaws.com/quandl-static-content/Documents/Quandl+-+Pandas,+SciPy,+NumPy+Cheat+Sheet.pdf) y [Official docs](https://docs.scipy.org/doc/numpy/)